# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Rapid Control Prototyping"

disableLanguages = ["fr"]

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://lubin.kerhuel.eu/"
#disableKinds = ["404"]
#canonifyURLs = true



# Enable comments by entering your Disqus shortname
disqusShortname = ""

ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$","ressources"]

############################
## Advanced options below ##
############################

[security.funcs]
  getenv = ["^HUGO_","^WC_"]
  
# Name of Academic theme folder in `themes/`.
theme = "academic/wowchemy"

# Get last modified date for content from Git?
enableGitInfo = true

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

enableRobotsTXT = true

removePathAccents = true 

summaryLength = 30  # Listing summary length in words. Also, see `abstract_length` in `params.toml`.
paginate = 16  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
# preserveTaxonomyNames = true

# Workaround Hugo publishing taxonomy URLs as plurals - consistently use singular across Academic.
[permalinks]
  # If only creating events which are talks, we can optimize event URLs for talks.
  event = "/talk/:slug/"
  # Workaround Hugo publishing taxonomy URLs as plurals - consistently use singular across Academic.
  tags = "/tag/:slug/"
  categories = "/category/:slug/"
  publication_types = "/publication-type/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON", "WebAppManifest", "headers", "redirects"]
  section = [ "HTML", "RSS" ]

# adding this break card multicolumn on main page.
#[params]
#  require_isotope = false  
#  [params.cms]
#    netlify_cms = false  

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

# # Configure BlackFriday Markdown rendering.
# #   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
# [blackfriday]
#   hrefTargetBlank = false  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
#   angledQuotes = false
#   latexDashes = true
#   extensions = ["backslashLineBreak"]

#[markup]
#  #defaultMarkdownHandler = "blackFriday"
#  defaultMarkdownHandler = "goldmark"
#  [markup.blackFriday]
#    angledQuotes = false
#    footnoteAnchorPrefix = ""
#    footnoteReturnLinkContents = ""
#    fractions = true
#    hrefTargetBlank = false
#    latexDashes = true
#    nofollowLinks = false
#    noreferrerLinks = false
#    plainIDAnchors = true
#    skipHTML = false
#    smartDashes = true
#    smartypants = true
#    smartypantsQuotesNBSP = false
#    taskLists = true
#    extensions = ["backslashLineBreak"]
#  [markup.goldmark]
#    [markup.goldmark.extensions]
#      definitionList = true
#      footnote = true
#      linkify = true
#      strikethrough = true
#      table = true
#      taskList = true
#      typographer = true
#    [markup.goldmark.parser]
#      attribute = true
#      autoHeadingID = true
#    [markup.goldmark.renderer]
#      hardWraps = false
#      unsafe = true
#      xHTML = true
#  [markup.highlight]
#    codeFences = false
#    hl_Lines = ""
#    lineNoStart = 1
#    lineNos = true
#    lineNumbersInTable = true
#    noClasses = false
#    style = "vs2015" #"monokai"
#    tabWidth = 4
#  [markup.tableOfContents]
#    endLevel = 3
#    startLevel = 2

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
    style = "vs2015" #"monokai"
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3    

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

# Related content.
[related]
  threshold = 80.0
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "title"
    weight = 60.0

  [[related.indices]]
    name = "summary"
    weight = 50.0

  [[related.indices]]
    name = "tags"
    weight = 80.0

  [[related.indices]]
    name = "categories"
    weight = 70.0
