[build]
  command = "hugo --gc --minify -D"
  publish = "public"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_VERSION = "0.58.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
